# mosquitto.conf — Config du broker SAI (Mosquitto 2.x).
#
# Deux listeners exposes par CE fichier :
#   - 8883  (MQTT TLS, CA autosignee)            → ESP32 / backend/ CLI
#   - 9001  (WebSocket SANS TLS, dev)            → frontend web (temps reel)

# ─── General ───
per_listener_settings true
persistence true
persistence_location B:/Gilw_Emmanuel/projet/Academiques/projet_integrateur/projet_integrateur/mosquitto/data

# ─── Listener TLS : 8883 ───
listener 8883 0.0.0.0
protocol mqtt
listener_allow_anonymous false
password_file B:/Gilw_Emmanuel/projet/Academiques/projet_integrateur/projet_integrateur/mosquitto/passwd
acl_file B:/Gilw_Emmanuel/projet/Academiques/projet_integrateur/projet_integrateur/mosquitto/acl
cafile B:/Gilw_Emmanuel/projet/Academiques/projet_integrateur/projet_integrateur/mosquitto/certs/mosquitto_ca.crt
certfile B:/Gilw_Emmanuel/projet/Academiques/projet_integrateur/projet_integrateur/mosquitto/certs/mosquitto_server.crt
keyfile B:/Gilw_Emmanuel/projet/Academiques/projet_integrateur/projet_integrateur/mosquitto/certs/mosquitto_server.key
tls_version tlsv1.2

# ─── Listener WebSocket dev : 9001 (frontend React) ───
listener 9001 0.0.0.0
protocol websockets
listener_allow_anonymous false
password_file B:/Gilw_Emmanuel/projet/Academiques/projet_integrateur/projet_integrateur/mosquitto/passwd
acl_file B:/Gilw_Emmanuel/projet/Academiques/projet_integrateur/projet_integrateur/mosquitto/acl

# ─── Logs vers console ───
log_dest stdout
log_type all
connection_messages true
